//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string job_title { get; set; }
        public string gender { get; set; }
        public System.DateTime birth_date { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
